{% set name = "apache-airflow-providers-openlineage" %}
{% set version = "1.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_openlineage-{{ version }}.tar.gz
  sha256: f6f1d6c40e3f33fee6b212c7114316430fe583540111a891a795b381268f3e48

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8,<4.dev0
    - apache-airflow-providers-common-sql >=1.6.0
    - apache-airflow >=2.7.0
    - attrs >=22.2
    - openlineage-integration-common >=1.16.0
    - openlineage-python >=1.16.0

test:
  imports:
    - airflow.providers.openlineage
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-openlineage for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/openlineage/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-openlineage/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
