{% set name = "apache-airflow-providers-openlineage" %}
{% set version = "1.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_openlineage-{{ version }}.tar.gz
  sha256: 1884bfcb705c1bff278cae418a13692d27882c64b716e79e3aae8c34e749ac20

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.10.1
    - pip
  run:
    - python >={{ python_min }}
    - apache-airflow-providers-common-compat >=1.2.1
    - apache-airflow-providers-common-sql >=1.20.0
    - apache-airflow >=2.8.0
    - attrs >=22.2
    - openlineage-integration-common >=1.24.2
    - openlineage-python >=1.24.2

test:
  imports:
    - airflow.providers.openlineage
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-openlineage for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/openlineage/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-openlineage/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
